### ISSUE TITLE
Call for student volunteers

### ISSUE THREAD

**Issue by napulen** [ismir/ISMIR2020#17]
Are we having a call for student volunteers? If so, thinks that could be included in the corresponding page:
- Eligibility
- Responsibilities
- Application process

**Comment by emilyhopkins** [comment]
Yes, we will, Caroline Traube is the Volunteer Committee chair although she hasn't finalized anything yet. We can likely adapt a lot of this: https://wp.nyu.edu/ismir2016/call-for-participation/call-for-volunteers/
