### ISSUE TITLE
Broken link on ISMIR2020 website, master is not up-to-date

### ISSUE THREAD

**Issue by idilsulo** [ismir/ISMIR2020#43]
There is a typo in one of the links on the updated version of the website. I wanted to open a pull request but the repository is not up-to-date at least for `hamr.md`. 

Is it possible to fix this problem?

**Comment by napulen** [comment]
Thanks for reaching out. The latest version of the website is located here: https://github.com/DDMAL/ISMIR2020/tree/prodAWS

If you can submit the PR against that branch, I'll be happy to merge it.

**Comment by napulen** [comment]
And sorry about the misleading `master` branch in this repo, by the way. We had last-minute issues during the conference that forced us to make that call.

**Comment by idilsulo** [comment]
@napulen No problem.  So if I understood right, I should be opening the PR on the production branch (`prodAWS`) of the clone (`DDMAL/ISMIR2020`) instead of the production branch (`prodAWS`) of the original repo (` ismir/ISMIR2020 `). Is this correct?

**Comment by napulen** [comment]
@idilsulo Yes :) That'd be perfect.

Thanks!
